### PR TITLE
set mimetype of response if set on key

### PR DESCRIPTION
**Pull request by ewdurbin**
This change is [Reviewable](https://reviewable.io/reviews/reversefold/python-s3proxy/2)

### CODE REVIEW

**Comment by reversefold** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[s3proxy/__init__.py, line 64 at r2](https://reviewable.io:443/reviews/reversefold/python-s3proxy/2#-L3iL8wqcqsezz0_0EZb:-L3iL8wqcqsezz0_0EZc:b-xhwm42) ([raw file](https://github.com/reversefold/python-s3proxy/blob/ad22cee86eb20ea90969de4cbd643e2b2c26917b/s3proxy/__init__.py#L64)):*
> ```Python
>             if key is None:
>                 # If we can't find a file, try it with .html suffix
>                 key = self.bucket.get_key(full_path + '.html')
> ```

What is the rationale for this change? The original purpose of this package is to just be an HTTP proxy essentially. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/reversefold/python-s3proxy/2)*

**Comment by ewdurbin** [comment]
@reversefold my assumption is that @iterion pushed some commits from the fork being run at my previous place of employ, not realizing they would end up on this PR.

**Comment by iterion** [comment]
Indeed - happy to move this stuff to a separate branch if we want to keep this original PR intact?

**Comment by jamescarr** [comment]
@reversefold this branch is updated to remove our customizations.

**Comment by reversefold** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/reversefold/python-s3proxy/2#-:-L6IzG7KXHiaZq9AmSDn:bnfp4nl)*

**Comment by reversefold** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/reversefold/python-s3proxy/2)*

**Pull request merged**
